"use client";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { useEffect, useState } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Starfield from "react-starfield";
import { AnimatePresence } from "framer-motion";
import "./globals.css";
import AnimatedCursor from "react-animated-cursor";
import SplashScreen from "@/components/Splashscreen";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => {
      setIsLoading(false);
    }, 2000); // Adjust the timeout as needed

    return () => clearTimeout(timer);
  }, []);

  return (
    <html lang="en">
      <head>
        <title>Jaydeep Khandla | Full Stack Developer</title>
        <meta name="description" content="Jaydeep Khandla | Full Stack Developer" />
      </head>
      <body className={inter.className}>
        <Starfield
          starCount={10000}
          starColor={[255, 255, 255]}
          speedFactor={0.05}
          backgroundColor="black"
        />
        <AnimatePresence>
          <AnimatedCursor
            innerSize={8}
            outerSize={35}
            outerScale={2}
            innerStyle={{
              mixBlendMode: "exclusion",
              backgroundColor: "rgba(255, 255, 255)",
            }}
            outerAlpha={0}
            outerStyle={{
              mixBlendMode: "exclusion",
              backgroundColor: "rgba(255, 255, 255)",
            }}
            clickables={["button", "a"]}
            trailingSpeed={8}
          />
          {isLoading ? <SplashScreen key="splash" /> : <>{children}</>}
          {/* <Analytics />
          <SpeedInsights /> */}
        </AnimatePresence>
      </body>
    </html>
  );
}
